# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yard-amp}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Edgar"]
  s.date = %q{2010-05-12}
  s.description = %q{yard-amp is a YARD plugin that enables the automatic creation of YARD documentation from amp command declarations.}
  s.email = %q{michael.j.edgar@dartmouth.edu}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardoc/checksums",
     ".yardoc/objects/YARD/Amp.dat",
     ".yardoc/objects/YARD/Amp/ModernCommandHandler.dat",
     ".yardoc/objects/YARD/Amp/ModernCommandHandler/commands_module_i.dat",
     ".yardoc/objects/YARD/Amp/ModernCommandHandler/process_i.dat",
     ".yardoc/objects/root.dat",
     ".yardoc/proxy_types",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/yard-amp.rb",
     "lib/yard-amp/modern_handler.rb",
     "lib/yard-amp/parsing_helpers.rb",
     "spec/examples/example_helper.rb",
     "spec/examples/examples/simple_command.rb.txt",
     "spec/parsing_helpers_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/yard-amp_spec.rb",
     "yard-amp.gemspec"
  ]
  s.homepage = %q{http://github.com/michaeledgar/yard-amp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Automatically create YARD documentation for Amp commands.}
  s.test_files = [
    "spec/examples/example_helper.rb",
     "spec/parsing_helpers_spec.rb",
     "spec/spec_helper.rb",
     "spec/yard-amp_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yard>, [">= 0.4.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<yard>, [">= 0.4.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<yard>, [">= 0.4.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end
